# Generated by Django 5.0 on 2023-12-08 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claider', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('title', models.CharField(blank=True, max_length=55, null=True, verbose_name='Направление')),
            ],
            options={
                'verbose_name': 'Направление Института',
                'verbose_name_plural': 'Направление Института',
            },
        ),
    ]
