# Generated by Django 5.0 on 2023-12-09 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claider', '0005_laboratory_scientificbase_alter_gallery_year'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ScientificBase',
            new_name='Base',
        ),
    ]
