# Generated by Django 5.0 on 2023-12-11 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claider', '0006_rename_scientificbase_base'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='base',
            options={'verbose_name': ' Base', 'verbose_name_plural': 'Bases'},
        ),
    ]
