# Generated by Django 5.0 on 2023-12-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изоброжение')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название статьи')),
                ('subtitle', models.TextField(blank=True, max_length=255, null=True, verbose_name='Статья')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
            },
        ),
    ]
